import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
export function PrintReportTable({ data, dateRange }) {
    // Calculate Summary Stats
    const totalAmount = data.reduce((sum, row) => { var _a; return sum + (((_a = row.costs) === null || _a === void 0 ? void 0 : _a.total) || 0); }, 0);
    const grandTotalParcels = data.reduce((sum, row) => {
        var _a;
        const rowQty = ((_a = row.parcels) === null || _a === void 0 ? void 0 : _a.reduce((pSum, p) => pSum + p.quantity, 0)) || 0;
        return sum + rowQty;
    }, 0);
    // Calculate "Online" vs "Manual"
    const onlinePaid = data
        .filter(r => r.paymentType === 'Paid')
        .reduce((sum, r) => { var _a; return sum + (((_a = r.costs) === null || _a === void 0 ? void 0 : _a.total) || 0); }, 0);
    const onlineToPay = data
        .filter(r => r.paymentType === 'To Pay')
        .reduce((sum, r) => { var _a; return sum + (((_a = r.costs) === null || _a === void 0 ? void 0 : _a.total) || 0); }, 0);
    const onlineTotal = onlinePaid + onlineToPay;
    return (_jsxs("div", { className: "w-full text-black font-sans text-[10px]", children: [_jsxs("div", { className: "mb-1 font-bold", children: ["Date: ", dateRange || new Date().toLocaleDateString()] }), _jsxs("table", { className: "w-full border-collapse border border-black mb-4", children: [_jsx("thead", { children: _jsxs("tr", { className: "bg-gray-200", children: [_jsx("th", { className: "border border-black px-1 py-1 text-left w-8", children: "SR..." }), _jsx("th", { className: "border border-black px-1 py-1 text-left", children: "LR NUM..." }), _jsx("th", { className: "border border-black px-1 py-1 text-left", children: "B. Branch" }), _jsx("th", { className: "border border-black px-1 py-1 text-left", children: "Dest" }), _jsx("th", { className: "border border-black px-1 py-1 text-left", children: "Sender" }), _jsx("th", { className: "border border-black px-1 py-1 text-left", children: "Reciever" }), _jsx("th", { className: "border border-black px-1 py-1 text-left", children: "Reciever No." }), _jsx("th", { className: "border border-black px-1 py-1 text-left w-8", children: "Art" }), _jsx("th", { className: "border border-black px-1 py-1 text-left", children: "Art Type" }), _jsx("th", { className: "border border-black px-1 py-1 text-left", children: "LR Type" }), _jsx("th", { className: "border border-black px-1 py-1 text-left", children: "Total" })] }) }), _jsx("tbody", { children: data.map((row, index) => {
                            var _a, _b, _c, _d;
                            // Calculate total Art (quantity)
                            const totalQty = ((_a = row.parcels) === null || _a === void 0 ? void 0 : _a.reduce((sum, p) => sum + p.quantity, 0)) || 0;
                            // Main Art Type (first one or joined)
                            const artType = ((_c = (_b = row.parcels) === null || _b === void 0 ? void 0 : _b[0]) === null || _c === void 0 ? void 0 : _c.itemType) || "-";
                            return (_jsxs("tr", { children: [_jsx("td", { className: "border border-black px-1 py-0.5", children: index + 1 }), _jsx("td", { className: "border border-black px-1 py-0.5", children: row.lrNumber }), _jsx("td", { className: "border border-black px-1 py-0.5 truncate max-w-[100px]", children: row.fromBranch }), _jsx("td", { className: "border border-black px-1 py-0.5 truncate max-w-[100px]", children: row.toBranch }), _jsx("td", { className: "border border-black px-1 py-0.5 truncate max-w-[120px]", children: row.sender.name }), _jsx("td", { className: "border border-black px-1 py-0.5 truncate max-w-[120px]", children: row.receiver.name }), _jsx("td", { className: "border border-black px-1 py-0.5", children: row.receiver.mobile }), _jsx("td", { className: "border border-black px-1 py-0.5", children: totalQty }), _jsx("td", { className: "border border-black px-1 py-0.5 truncate max-w-[100px]", children: artType }), _jsx("td", { className: "border border-black px-1 py-0.5", children: row.paymentType }), _jsx("td", { className: "border border-black px-1 py-0.5", children: ((_d = row.costs) === null || _d === void 0 ? void 0 : _d.total) || 0 })] }, row.id || index));
                        }) })] }), _jsxs("div", { className: "w-[400px]", children: [_jsxs("table", { className: "w-full border-collapse border border-black", children: [_jsx("thead", { children: _jsxs("tr", { className: "bg-gray-100", children: [_jsx("th", { className: "border border-black px-2 py-1 text-left", children: "Type" }), _jsx("th", { className: "border border-black px-2 py-1 text-left", children: "Paid" }), _jsx("th", { className: "border border-black px-2 py-1 text-left", children: "To Pay" }), _jsx("th", { className: "border border-black px-2 py-1 text-left", children: "Total Amount" })] }) }), _jsxs("tbody", { children: [_jsxs("tr", { children: [_jsx("td", { className: "border border-black px-2 py-1", children: "Online" }), _jsx("td", { className: "border border-black px-2 py-1", children: onlinePaid }), _jsx("td", { className: "border border-black px-2 py-1", children: onlineToPay }), _jsx("td", { className: "border border-black px-2 py-1 font-bold", children: onlineTotal })] }), _jsxs("tr", { children: [_jsx("td", { className: "border border-black px-2 py-1", children: "Manual" }), _jsx("td", { className: "border border-black px-2 py-1", children: "0" }), _jsx("td", { className: "border border-black px-2 py-1", children: "0" }), _jsx("td", { className: "border border-black px-2 py-1", children: "0" })] }), _jsxs("tr", { className: "bg-gray-100 font-bold", children: [_jsx("td", { className: "border border-black px-2 py-1", children: "Total" }), _jsx("td", { className: "border border-black px-2 py-1", children: onlinePaid }), _jsx("td", { className: "border border-black px-2 py-1", children: onlineToPay }), _jsx("td", { className: "border border-black px-2 py-1", children: totalAmount })] })] })] }), _jsxs("div", { className: "mt-1 text-[10px] font-bold text-right border border-black p-1 bg-gray-100", children: ["Total Parcels : ", grandTotalParcels, " | Paid : ", onlinePaid, " | To Pay : ", onlineToPay] })] })] }));
}
