"use client";

import { useState, useEffect } from "react";
import { useBranchStore } from "@/frontend/lib/store";
import { BookingForm } from "@/frontend/components/booking/BookingForm";
import { ParcelList } from "@/frontend/components/booking/ParcelList";
import { PaymentBox } from "@/frontend/components/booking/PaymentBox";
import { Booking, Parcel, PaymentStatus, Branch } from "@/shared/types";
// import { v4 as uuidv4 } from "uuid"; // We might not have uuid installed, I'll use a simple random string generator or date
import { Printer } from "lucide-react";
import { useBranches } from "@/frontend/hooks/useBranches";
import { parcelService } from "@/frontend/services/parcelService";

// Simple ID generator if uuid is not available
const generateId = () => Math.random().toString(36).substr(2, 9);

export default function BookingDashboard() {
  // Services & State
  const { currentUser } = useBranchStore();
  const { branches: branchNames, branchObjects } = useBranches();
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Local State
  const [lrNumber, setLrNumber] = useState("PENDING"); // LR is generated by Server now
  const [isLocked, setIsLocked] = useState(false);

  // Initialize with sensible defaults. Authenticated user's branch takes precedence for "From".
  const [fromBranch, setFromBranch] = useState<Branch>("Branch A");
  const [toBranch, setToBranch] = useState<Branch>("Branch B");

  // Sync From Branch with Current User
  useEffect(() => {
    if (currentUser?.branch && currentUser.branch !== "Global") {
      setFromBranch(currentUser.branch as Branch);
    } else if (branchNames.length > 0) {
      // If Global or no user branch, default to first available branch
      if (!fromBranch || fromBranch === "Branch A") {
        setFromBranch(branchNames[0] as Branch);
      }
    }
  }, [currentUser, branchNames, fromBranch]);

  // Sync To Branch
  useEffect(() => {
    if (branchNames.length > 1) {
      // Ensure To Branch is not same as From Branch
      if (!toBranch || toBranch === "Branch B" || toBranch === fromBranch) {
        const alternate = branchNames.find(b => b !== fromBranch);
        if (alternate) setToBranch(alternate as Branch);
      }
    }
  }, [branchNames, fromBranch, toBranch]);

  const [sender, setSender] = useState({ name: "", mobile: "" });
  const [receiver, setReceiver] = useState({ name: "", mobile: "" });

  const [parcels, setParcels] = useState<Parcel[]>([
    { id: generateId(), quantity: 1, itemType: "White Sack", weight: 0, rate: 0 }
  ]);

  const [costs, setCosts] = useState({
    freight: 0,
    handling: 10,
    hamali: 0,
    total: 10
  });

  const [paymentType, setPaymentType] = useState<PaymentStatus>("Paid");

  // Auto-calculate Freight
  useEffect(() => {
    if (isLocked) return;
    const totalFreight = parcels.reduce((sum, p) => sum + (p.quantity * (p.rate || 0)), 0);
    setCosts(prev => ({
      ...prev,
      freight: totalFreight,
      total: totalFreight + prev.handling + prev.hamali
    }));
  }, [parcels, isLocked]);

  // Handlers
  const handleAddParcel = () => {
    setParcels([...parcels, { id: generateId(), quantity: 1, itemType: "White Sack", weight: 0, rate: 0 }]);
  };

  const handleRemoveParcel = (id: string) => {
    setParcels(parcels.filter(p => p.id !== id));
  };

  const handleParcelChange = (id: string, field: keyof Parcel, value: any) => {
    setParcels(parcels.map(p => p.id === id ? { ...p, [field]: value } : p));
  };

  const handleSave = async () => {
    if (costs.total <= 0) return;
    setIsSubmitting(true);

    // Try to find IDs
    const fromBranchId = branchObjects.find(b => b.name === fromBranch)?._id;
    const toBranchId = branchObjects.find(b => b.name === toBranch)?._id;

    const bookingData: Booking = {
      // Temporary ID, ignored by server
      id: generateId(),
      lrNumber: "GENERATING...",
      // Use Resolved ID or fallback (which will likely fail if it's a name)
      fromBranch: fromBranchId || fromBranch,
      toBranch: toBranchId || toBranch,
      date: new Date().toISOString(),
      sender,
      receiver,
      parcels,
      costs,
      paymentType,
      status: "Booked"
    };

    console.log("Final Payload:", bookingData);

    const { data: createdParcel, error } = await parcelService.createBooking(bookingData, currentUser?.id || '');

    if (error) {
      setIsSubmitting(false);
      alert("Booking Failed: " + error.message); // In real app, use Toast
      return;
    }

    if (createdParcel) {
      setLrNumber(createdParcel.lr_number);
      setIsLocked(true);
      setIsSubmitting(false);

      // Simulate Print
      setTimeout(() => {
        window.print();
      }, 500);
    }
  };

  const handleReset = () => {
    setIsLocked(false);
    setSender({ name: "", mobile: "" });
    setReceiver({ name: "", mobile: "" });
    setParcels([{ id: generateId(), quantity: 1, itemType: "White Sack", weight: 0, rate: 0 }]);
    setCosts({ freight: 0, handling: 10, hamali: 0, total: 10 });
    setPaymentType("Paid");
    setLrNumber("PENDING");
  };

  return (
    <div className="max-w-7xl mx-auto">
      {/* ... (keep header) */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">New Booking</h1>
          <p className="text-slate-500 text-sm">Create a new parcel booking</p>
        </div>

        <div className="bg-white px-4 py-2 rounded-lg border border-slate-200 shadow-sm flex items-center gap-3">
          <span className="text-xs text-slate-500 uppercase tracking-wide font-semibold">LR Number</span>
          <span className="text-xl font-mono font-bold text-blue-600">{lrNumber}</span>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Panel: Forms */}
        <div className="lg:col-span-2 space-y-6">
          <BookingForm
            title="Sender Details"
            type="sender"
            values={sender}
            onChange={(field, val) => setSender({ ...sender, [field]: val })}
            disabled={isLocked}
            branch={fromBranch}
            onBranchChange={setFromBranch}
            branchLabel="Dispatch Branch"
            availableBranches={branchNames}
          />

          <BookingForm
            title="Receiver Details"
            type="receiver"
            values={receiver}
            onChange={(field, val) => setReceiver({ ...receiver, [field]: val })}
            disabled={isLocked}
            branch={toBranch}
            onBranchChange={setToBranch}
            branchLabel="Dest. Branch"
            availableBranches={branchNames}
          />

          <ParcelList
            parcels={parcels}
            onAdd={handleAddParcel}
            onRemove={handleRemoveParcel}
            onChange={handleParcelChange}
            disabled={isLocked}
          />
        </div>

        {/* Right Panel: Payment */}
        <div className="lg:col-span-1">
          <PaymentBox
            costs={costs}
            paymentType={paymentType}
            onChange={(field, val) => {
              if (field === 'paymentType') setPaymentType(val);
              else {
                setCosts(prev => {
                  const updated = { ...prev, [field]: val };
                  return { ...updated, total: updated.freight + updated.handling + updated.hamali };
                });
              }
            }}
            onSave={handleSave}
            isLocked={isLocked}
          />

          {isLocked && (
            <button
              onClick={handleReset}
              className="w-full mt-4 py-2 text-slate-500 hover:text-blue-600 font-medium text-sm transition-colors"
            >
              Start New Booking
            </button>
          )}
        </div>
      </div>

      {/* Hidden Print Receipt */}
      <div className="hidden print:block absolute top-0 left-0 w-full h-full bg-white z-50 p-8">
        <div className="text-center mb-8 border-b pb-4 border-slate-900">
          <h1 className="text-3xl font-bold mb-2">ABCD Logistics</h1>
          <p className="text-sm">Transport & Parcel Services</p>
          <p className="text-sm mt-1">{fromBranch}</p>
        </div>

        <div className="flex justify-between mb-8">
          <div>
            <p className="text-sm text-slate-500">LR Number</p>
            <p className="text-xl font-bold font-mono">{lrNumber}</p>
          </div>
          <div>
            <p className="text-sm text-slate-500">Date</p>
            <p className="font-medium">{new Date().toLocaleDateString()}</p>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-8 mb-8">
          <div>
            <p className="font-bold border-b border-slate-300 mb-2 pb-1">Sender</p>
            <p>{sender.name}</p>
            <p>{sender.mobile}</p>
          </div>
          <div>
            <p className="font-bold border-b border-slate-300 mb-2 pb-1">Receiver</p>
            <p>{receiver.name}</p>
            <p>{receiver.mobile}</p>
          </div>
        </div>

        <table className="w-full mb-8 text-left">
          <thead>
            <tr className="border-b border-slate-300">
              <th className="pb-2">Qty</th>
              <th className="pb-2">Item</th>

            </tr>
          </thead>
          <tbody>
            {parcels.map((p, i) => (
              <tr key={i} className="border-b border-slate-100">
                <td className="py-2">{p.quantity}</td>
                <td className="py-2">{p.itemType}</td>

              </tr>
            ))}
          </tbody>
        </table>

        <div className="border-t border-slate-900 pt-4 flex justify-between items-center">
          <div>
            <p className="text-sm font-bold uppercase">{paymentType}</p>
          </div>
          <div className="text-right">
            <p className="text-2xl font-bold">₹ {costs.total.toFixed(2)}</p>
          </div>
        </div>

        <div className="mt-12 text-center text-xs text-slate-400">
          <p>Thank you for shipping with ABCD Logistics</p>
        </div>
      </div>
    </div>
  );
}
