import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import ExcelJS from 'exceljs';
import { Response } from 'express';

// Extend jsPDF to include autoTable
declare module 'jspdf' {
    interface jsPDF {
        autoTable: (options: any) => jsPDF;
    }
}

export const exportService = {
    async generatePDF(res: Response, data: any[], metadata: { branchName: string, reportType: string, dateRange: string, generatedBy: string }) {
        const doc = new jsPDF();
        const timestamp = new Date().toLocaleString();

        // Header
        doc.setFontSize(18);
        doc.text('SAVAN LOGISTICS', 105, 15, { align: 'center' });
        doc.setFontSize(12);
        doc.text(`Report: ${metadata.reportType}`, 105, 22, { align: 'center' });

        // Metadata Box
        doc.setFontSize(10);
        doc.text(`Branch: ${metadata.branchName}`, 14, 35);
        doc.text(`Date Range: ${metadata.dateRange}`, 14, 40);
        doc.text(`Generated By: ${metadata.generatedBy}`, 14, 45);
        doc.text(`Timestamp: ${timestamp}`, 14, 50);

        // Data Table
        const tableColumn = ["LR No", "Sender", "Receiver", "Route", "Amount", "Status"];
        const tableRows: any[] = [];

        data.forEach(item => {
            const rowData = [
                item.lrNumber,
                item.sender.name,
                item.receiver.name,
                `${item.fromBranch.name} -> ${item.toBranch.name}`,
                `Rs. ${item.costs.total.toFixed(2)}`,
                item.status
            ];
            tableRows.push(rowData);
        });

        doc.autoTable({
            head: [tableColumn],
            body: tableRows,
            startY: 55,
            theme: 'grid',
            headStyles: { fillColor: [41, 128, 185] },
            styles: { fontSize: 8 }
        });

        const pdfBuffer = doc.output('arraybuffer');
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=Report_${Date.now()}.pdf`);
        res.send(Buffer.from(pdfBuffer));
    },

    async generateExcel(res: Response, data: any[], metadata: { branchName: string, reportType: string, dateRange: string, generatedBy: string }) {
        const workbook = new ExcelJS.Workbook();
        const worksheet = workbook.addWorksheet('Report');

        // Styles
        const headerStyle: Partial<ExcelJS.Style> = {
            font: { bold: true, size: 14 },
            alignment: { horizontal: 'center' }
        };

        // Title & Metadata
        worksheet.mergeCells('A1:F1');
        worksheet.getCell('A1').value = 'SAVAN LOGISTICS - ' + metadata.reportType;
        worksheet.getCell('A1').style = headerStyle;

        worksheet.addRow(['Branch:', metadata.branchName]);
        worksheet.addRow(['Date Range:', metadata.dateRange]);
        worksheet.addRow(['Generated By:', metadata.generatedBy]);
        worksheet.addRow(['Timestamp:', new Date().toLocaleString()]);
        worksheet.addRow([]); // Spacer

        // Table Header
        worksheet.addRow(["LR Number", "Sender", "Receiver", "From", "To", "Amount", "Status", "Remarks"]);
        worksheet.getRow(7).font = { bold: true };

        // Data
        data.forEach(item => {
            worksheet.addRow([
                item.lrNumber,
                item.sender.name,
                item.receiver.name,
                item.fromBranch.name,
                item.toBranch.name,
                item.costs.total,
                item.status,
                item.remarks || '-'
            ]);
        });

        res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        res.setHeader('Content-Disposition', `attachment; filename=Report_${Date.now()}.xlsx`);

        await workbook.xlsx.write(res);
        res.end();
    }
};
